<?php

namespace Kountac\CommentairesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * commentairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentairesRepository extends EntityRepository
{
    public function commentairesProduit($id) 
    {
        $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.produit = :id')
                   ->setParameter('id', $id) 
                ;      
        return  $qb->getQuery()->getResult();
    }
}
