<?php

namespace Kountac\KountacBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TousCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends EntityRepository
{
    public function getCategoriesByName() 
    {
        return $this->getEntityManager()
                ->createQuery('SELECT c FROM KountacBundle:Categories c WHERE c.parent IS NULL')
                ->getResult();
    }
    
    public function getCategoriesByLastChild() 
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.parent != :null')
                ->andWhere('u.parent != :null')
                ->andWhere('SIZE(u.children) = :seuil')
                ->orderBy('u.nom', 'DESC')
                ->setParameter('seuil', '0')
                ->setParameter('null', 'NULL');       
        return $qb->getQuery()->getResult();
    }
}
