<?php

namespace Kountac\KountacBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends EntityRepository
{
    public function getCommandesByUser($user) 
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.utilisateur = :user')
                ->setParameter('user', $user)
                ->orderBy('u.id', 'DESC')
        ;
        return $qb->getQuery()->getResult();
    }
    
    public function getCommandesByUser_produit($user) 
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.utilisateur = :user')
                ->andWhere('u.produit != :null')
                ->andWhere('u.acheter = :notok')
                ->setParameter('user', $user)
                ->setParameter('notok', '0')
                ->setParameter('null', 'NULL')
                ->orderBy('u.id', 'DESC')
        ;
        return $qb->getQuery()->getResult();
    }
    
    public function getCommandesByUser_produit_acheter($user) 
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.utilisateur = :user')
                ->andWhere('u.produit != :null')
                ->andWhere('u.acheter = :notok')
                ->setParameter('user', $user)
                ->setParameter('notok', '1')
                ->setParameter('null', 'NULL')
                ->orderBy('u.id', 'DESC')
        ;
        return $qb->getQuery()->getResult();
    }
    
    public function getCommandesByPro($user) 
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.utilisateur = :user')
                ->andWhere('u.terminer = :terminer')
                ->setParameter('user', $user)
                ->setParameter('terminer', '1')
                ->orderBy('u.id', 'DESC')
        ;
        return $qb->getQuery()->getResult();
    }
    
    public function getAllCommandesByPro($user) 
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.utilisateur = :user')
                ->andWhere('u.terminer = :terminer')
                ->setParameter('user', $user)
                ->setParameter('terminer', '0')
                ->orderBy('u.id', 'DESC')
        ;
        return $qb->getQuery()->getResult();
    }
}
