<?php

namespace Kountac\KountacBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Libelles_motifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Libelles_motifRepository extends EntityRepository
{
    public function findByNouveaute() 
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->orderBy('u.id', 'DESC')
                ;
        return $qb->getQuery()->getResult();
    }
}
