<?php

namespace Kountac\KountacBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Libelles_motifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MannequinRepository extends EntityRepository
{
    public function findByDisponible($user) 
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.statut_mannequin = :disponible')
                ->orWhere('u.marque = :user')
                ->orderBy('u.id', 'DESC')
                ->setParameter('disponible', 'disponible')
                ->setParameter('user', $user)
                ;
        return $qb->getQuery()->getResult();
    }
    
    public function findByMarque($user) 
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.marque = :user')
                ->orderBy('u.id', 'DESC')
                ->setParameter('user', $user)
                ;
        return $qb->getQuery()->getResult();
    }
    
    public function FindMannequin($nom) 
    {
        $qb = $this->createQueryBuilder('m')
                ->select('m')
                ->where('m.nom_mannequin like :nom')
                ->setParameter('nom', '%'.$nom.'%')
                ->setMaxResults(1);
        return $qb->getQuery()->getResult();
    }
    
    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('u')
                ->Select('u')
                ->Where('u.id IN (:array)')
                ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }
}
