<?php

namespace Kountac\KountacBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationsRepository extends EntityRepository
{
    public function getReservationsByUser($user) 
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.utilisateur = :user')
                ->setParameter('user', $user)
                ->orderBy('u.id', 'DESC')
        ;
        return $qb->getQuery()->getResult();
    }
    
    public function getReservationsByMarque($user) 
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.marque = :user')
                ->setParameter('user', $user)
                ->orderBy('u.id', 'DESC')
        ;
        return $qb->getQuery()->getResult();
    }
}
