<?php

namespace Utilisateurs\UtilisateursBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MesuresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesuresRepository extends EntityRepository
{
    public function getMesuresByUser($user) 
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.utilisateur = :user')
                ->setParameter('user', $user)
                ->orderBy('u.id', 'DESC')
        ;
        return $qb->getQuery()->getResult();
    }
}
