<?php

namespace Utilisateurs\UtilisateursBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateursRepository extends EntityRepository
{
    public function getAllMarques() 
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.marque != :null')
                ->setParameter('null', 'NULL')
                ->orderBy('u.id', 'DESC')
        ;
        return $qb->getQuery()->getResult();
    }
}
