reserve_new:
    path:     /new_{id}/
    defaults: { _controller: UtilisateursBundle:Reservations:new }

reserve_delete:
    path:     /delete_{id}/
    defaults: { _controller: UtilisateursBundle:Reservations:delete }    
    
reserve_index:
    path:     /
    defaults: { _controller: UtilisateursBundle:Reservations:index }