kountac_devise_cfa:
    path:     /cfa
    defaults: { _controller: KountacBundle:Devise:cfaDevise }

kountac_devise_euro:
    path:     /euro
    defaults: { _controller: KountacBundle:Devise:euroDevise }
    
kountac_devise_all:
    path:     /all
    defaults: { _controller: KountacBundle:Devise:allDevise }
    
kountac_devise_livre:
    path:     /livre
    defaults: { _controller: KountacBundle:Devise:livreDevise }
    
kountac_devise_usa:
    path:     /usa
    defaults: { _controller: KountacBundle:Devise:usaDevise }
    
kountac_devise_naira:
    path:     /naira
    defaults: { _controller: KountacBundle:Devise:nairaDevise }