panier:
    path:     /
    defaults: { _controller: KountacBundle:Panier:panier }

ajoutpanier:
    path:     /add/{id}
    defaults: { _controller: KountacBundle:Panier:ajoutpanier }

supprimerpanier:
    path:     /delete/{id}
    defaults: { _controller: KountacBundle:Panier:supprimerpanier }     