wishlist:
    path:     /
    defaults: { _controller: KountacBundle:Wishlist:wishlist }
    
ajoutwishlist:
    path:     /add/{id}
    defaults: { _controller: KountacBundle:Wishlist:ajoutwishlist }
    
ajoutToutpanier:
    path:     /add_all
    defaults: { _controller: KountacBundle:Wishlist:ajoutToutpanier }

supprimerwishlist:
    path:     /delete/{id}
    defaults: { _controller: KountacBundle:Wishlist:supprimerwishlist } 