compare:
    path:     /
    defaults: { _controller: KountacBundle:Compare:compare }
    
ajoutcompare:
    path:     /add/{id}
    defaults: { _controller: KountacBundle:Compare:ajoutcompare }

supprimercompare:
    path:     /delete/{id}
    defaults: { _controller: KountacBundle:Compare:supprimercompare }
    
supprimercompareAside:
    path:     /wishlist/delete/{id}
    defaults: { _controller: KountacBundle:Compare:supprimercompareAside }
    
supprimercompareAll:
    path:     /wishlist/delete_all
    defaults: { _controller: KountacBundle:Compare:supprimercompareAside_all }