adminAchats_index:
    path:     /
    defaults: { _controller: "KountacBundle:AchatsAdmin:index" }
    
adminAchats_delete:
    path:     /{id}/delete
    defaults: { _controller: "KountacBundle:AchatsAdmin:delete" }