adminCategories_index:
    path:     /
    defaults: { _controller: "KountacBundle:CategoriesAdmin:index" }
    methods:  GET

adminCategories_new:
    path:     /new
    defaults: { _controller: "KountacBundle:CategoriesAdmin:new" }
    methods:  [GET, POST]

adminCategories_edit:
    path:     /{id}/edit
    defaults: { _controller: "KountacBundle:CategoriesAdmin:edit" }
    methods:  [GET, POST]

adminCategories_delete:
    path:     /{id}/delete
    defaults: { _controller: "KountacBundle:CategoriesAdmin:delete" }
