adminCollections_index:
    path:     /
    defaults: { _controller: "KountacBundle:CollectionsAdmin:index" }
    methods:  GET

adminCollections_new:
    path:     /new
    defaults: { _controller: "KountacBundle:CollectionsAdmin:new" }
    methods:  [GET, POST]

adminCollections_edit:
    path:     /{id}/edit
    defaults: { _controller: "KountacBundle:CollectionsAdmin:edit" }
    methods:  [GET, POST]

adminCollections_delete:
    path:     /{id}/delete
    defaults: { _controller: "KountacBundle:CollectionsAdmin:delete" }
