adminCommandes_index:
    path:     /
    defaults: { _controller: "KountacBundle:CommandesAdmin:index" }
    methods:  GET

adminCommandes_show:
    path:     /{id}/show
    defaults: { _controller: "KountacBundle:CommandesAdmin:show" }

adminCommandes_mesures_new:
    path:     /new_mesures
    defaults: { _controller: "KountacBundle:CommandesAdmin:newMesures" }
    methods:  [GET, POST] 
    
adminCommandes_mesures_validation:
    pattern: /validation_mesures
    defaults: { _controller: KountacBundle:CommandesAdmin:validationMesure }
 
adminCommandes_new:
    path:     /new
    defaults: { _controller: "KountacBundle:CommandesAdmin:new" }
    methods:  [GET, POST]

adminCommandes_edit:
    path:     /{id}/edit
    defaults: { _controller: "KountacBundle:CommandesAdmin:edit" }
    methods:  [GET, POST]

adminCommandes_delete:
    path:     /{id}/delete
    defaults: { _controller: "KountacBundle:CommandesAdmin:delete" }

adminCommandes_envoyer:
    path:     /{id}_envoyer
    defaults: { _controller: "KountacBundle:CommandesAdmin:envoyer" }
    
adminCommandes_livrer:
    path:     /{id}_livrer
    defaults: { _controller: "KountacBundle:CommandesAdmin:livrer" }