adminProduits_index:
    path:     /
    defaults: { _controller: "KountacBundle:ProduitsAdmin:index" }
    methods:  GET

adminProduits_show:
    path:     /{id}/show
    defaults: { _controller: "KountacBundle:ProduitsAdmin:show" }
    methods:  [GET, POST]

adminProduits_new:
    path:     /new
    defaults: { _controller: "KountacBundle:ProduitsAdmin:new1" }
    methods:  [GET, POST]
    
adminProduits_new2:
    path:     /new2_{id}
    defaults: { _controller: "KountacBundle:ProduitsAdmin:new2" }
    
adminProduits_new3:
    path:     /add_new_taille_{id}
    defaults: { _controller: "KountacBundle:ProduitsAdmin:new3" }
    
adminProduits_new_motif:
    path:     /add_new_motif_{id}
    defaults: { _controller: "KountacBundle:ProduitsAdmin:addMotif" }
    methods:  [GET, POST]
    
adminProduits_new_mannequin:
    path:     /add_new_mannequin_{id}
    defaults: { _controller: "KountacBundle:ProduitsAdmin:addMannequin" }
    methods:  [GET, POST]

adminProduits_new_resume:
    path:     /new_resume_{id}
    defaults: { _controller: "KountacBundle:ProduitsAdmin:newResume" }
    methods:  [GET, POST]
    
adminProduits_edit_1:
    path:     /{id}/edit_1
    defaults: { _controller: "KountacBundle:ProduitsAdmin:edit_1" }
    methods:  [GET, POST]
    
adminProduits_edit_2:
    path:     /{id}/edit_2
    defaults: { _controller: "KountacBundle:ProduitsAdmin:edit_2" }
    methods:  [GET, POST]
    
adminProduits_edit_21:
    path:     /{id}/edit_21
    defaults: { _controller: "KountacBundle:ProduitsAdmin:edit_21" }
    methods:  [GET, POST]
    
adminProduits_edit_3:
    path:     /{id}/edit_3
    defaults: { _controller: "KountacBundle:ProduitsAdmin:edit_3" }
    methods:  [GET, POST]
    
adminProduits_edit_31:
    path:     /{id}/edit_31
    defaults: { _controller: "KountacBundle:ProduitsAdmin:edit_31" }
    methods:  [GET, POST]
    
adminProduits_edit_pays:
    path:     /{id}/edit_pays
    defaults: { _controller: "KountacBundle:ProduitsAdmin:editPays" }
    methods:  [GET, POST]
    
adminProduits_stock_epuise:
    path:     /stock_épuisé
    defaults: { _controller: "KountacBundle:ProduitsAdmin:stock" }
    methods:  GET
    
adminProduits_add_stock:
    path:     /{id}/add_stock
    defaults: { _controller: "KountacBundle:ProduitsAdmin:addStock" }
    methods:  [GET, POST]
    
adminProduits_add_prix_commande_cfa:
    path:     /{id}/add_prix_commande_cfa
    defaults: { _controller: "KountacBundle:ProduitsAdmin:addprixCommandeCfa" }
    methods:  [GET, POST]

adminProduits_delete:
    path:     /{id}/delete
    defaults: { _controller: "KountacBundle:ProduitsAdmin:delete" } 
    
adminProduits_deleteMotif:
    path:     /{id}/delete_Motif
    defaults: { _controller: "KountacBundle:ProduitsAdmin:deleteMotif" }  