adminCommentaires_index:
    path:     /
    defaults: { _controller: "CommentairesBundle:CommentairesAdmin:index" }
    methods:  GET

adminCommentaires_show:
    path:     /{id}/show
    defaults: { _controller: "CommentairesBundle:CommentairesAdmin:show" }
    methods:  GET

adminCommentaires_new:
    path:     /new
    defaults: { _controller: "CommentairesBundle:CommentairesAdmin:new" }
    methods:  [GET, POST]

adminCommentaires_edit:
    path:     /{id}/edit
    defaults: { _controller: "CommentairesBundle:CommentairesAdmin:edit" }
    methods:  [GET, POST]

adminCommentaires_delete:
    path:     /{id}/delete
    defaults: { _controller: "CommentairesBundle:CommentairesAdmin:delete" }