<?php

namespace Proxies\__CG__\Kountac\KountacBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produits_1 extends \Kountac\KountacBundle\Entity\Produits_1 implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'id', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'collection', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'produit_2', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'categorie', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'looks', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'marque', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'nom', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'matiere', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'description', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'conditions_utilisation', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'popularite', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'stock', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'dateajout', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'dateupdate', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'dateachat'];
        }

        return ['__isInitialized__', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'id', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'collection', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'produit_2', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'categorie', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'looks', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'marque', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'nom', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'matiere', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'description', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'conditions_utilisation', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'popularite', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'stock', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'dateajout', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'dateupdate', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\Produits_1' . "\0" . 'dateachat'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Produits_1 $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatiere($matiere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatiere', [$matiere]);

        return parent::setMatiere($matiere);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatiere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatiere', []);

        return parent::getMatiere();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setCollection(\Kountac\KountacBundle\Entity\Collections $collection = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCollection', [$collection]);

        return parent::setCollection($collection);
    }

    /**
     * {@inheritDoc}
     */
    public function getCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCollection', []);

        return parent::getCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(\Kountac\KountacBundle\Entity\Categories $categorie = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarque(\Utilisateurs\UtilisateursBundle\Entity\Utilisateurs $marque = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarque', [$marque]);

        return parent::setMarque($marque);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarque', []);

        return parent::getMarque();
    }

    /**
     * {@inheritDoc}
     */
    public function setPopularite($popularite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPopularite', [$popularite]);

        return parent::setPopularite($popularite);
    }

    /**
     * {@inheritDoc}
     */
    public function getPopularite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPopularite', []);

        return parent::getPopularite();
    }

    /**
     * {@inheritDoc}
     */
    public function addProduit2(\Kountac\KountacBundle\Entity\Produits_2 $produit2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduit2', [$produit2]);

        return parent::addProduit2($produit2);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduit2(\Kountac\KountacBundle\Entity\Produits_2 $produit2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduit2', [$produit2]);

        return parent::removeProduit2($produit2);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduit2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduit2', []);

        return parent::getProduit2();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateajout($dateajout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateajout', [$dateajout]);

        return parent::setDateajout($dateajout);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateajout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateajout', []);

        return parent::getDateajout();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateupdate($dateupdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateupdate', [$dateupdate]);

        return parent::setDateupdate($dateupdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateupdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateupdate', []);

        return parent::getDateupdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateachat($dateachat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateachat', [$dateachat]);

        return parent::setDateachat($dateachat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateachat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateachat', []);

        return parent::getDateachat();
    }

    /**
     * {@inheritDoc}
     */
    public function setStock($stock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStock', [$stock]);

        return parent::setStock($stock);
    }

    /**
     * {@inheritDoc}
     */
    public function getStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStock', []);

        return parent::getStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setConditionsUtilisation($conditionsUtilisation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConditionsUtilisation', [$conditionsUtilisation]);

        return parent::setConditionsUtilisation($conditionsUtilisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getConditionsUtilisation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConditionsUtilisation', []);

        return parent::getConditionsUtilisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLooks(\Kountac\KountacBundle\Entity\Idees_looks $looks = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLooks', [$looks]);

        return parent::setLooks($looks);
    }

    /**
     * {@inheritDoc}
     */
    public function getLooks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLooks', []);

        return parent::getLooks();
    }

}
