<?php

namespace Proxies\__CG__\Kountac\KountacBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SousAchats extends \Kountac\KountacBundle\Entity\SousAchats implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'id', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'utilisateur', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'marque', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'valider', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'effacer', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'euro', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'livre', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'usa', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'cfa', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'naira', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'date', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'reference', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'achat', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'statut', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'accepter', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'livraison', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'expedier', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'date_expedition', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'date_reception', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'statut_reception', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'date_livraison'];
        }

        return ['__isInitialized__', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'id', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'utilisateur', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'marque', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'valider', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'effacer', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'euro', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'livre', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'usa', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'cfa', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'naira', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'date', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'reference', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'achat', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'statut', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'accepter', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'livraison', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'expedier', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'date_expedition', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'date_reception', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'statut_reception', '' . "\0" . 'Kountac\\KountacBundle\\Entity\\SousAchats' . "\0" . 'date_livraison'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SousAchats $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setValider($valider)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValider', [$valider]);

        return parent::setValider($valider);
    }

    /**
     * {@inheritDoc}
     */
    public function getValider()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValider', []);

        return parent::getValider();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setReference($reference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', [$reference]);

        return parent::setReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', []);

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setAchat($achat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAchat', [$achat]);

        return parent::setAchat($achat);
    }

    /**
     * {@inheritDoc}
     */
    public function getAchat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAchat', []);

        return parent::getAchat();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccepter($accepter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccepter', [$accepter]);

        return parent::setAccepter($accepter);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccepter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccepter', []);

        return parent::getAccepter();
    }

    /**
     * {@inheritDoc}
     */
    public function setLivraison($livraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLivraison', [$livraison]);

        return parent::setLivraison($livraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getLivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivraison', []);

        return parent::getLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpedier($expedier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpedier', [$expedier]);

        return parent::setExpedier($expedier);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpedier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpedier', []);

        return parent::getExpedier();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate_expedition($date_expedition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate_expedition', [$date_expedition]);

        return parent::setDate_expedition($date_expedition);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate_expedition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate_expedition', []);

        return parent::getDate_expedition();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate_reception($date_reception)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate_reception', [$date_reception]);

        return parent::setDate_reception($date_reception);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate_reception()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate_reception', []);

        return parent::getDate_reception();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut_reception($statut_reception)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut_reception', [$statut_reception]);

        return parent::setStatut_reception($statut_reception);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut_reception()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut_reception', []);

        return parent::getStatut_reception();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate_livraison($date_livraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate_livraison', [$date_livraison]);

        return parent::setDate_livraison($date_livraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate_livraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate_livraison', []);

        return parent::getDate_livraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilisateur($utilisateur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilisateur', [$utilisateur]);

        return parent::setUtilisateur($utilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilisateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilisateur', []);

        return parent::getUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarque($marque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarque', [$marque]);

        return parent::setMarque($marque);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarque', []);

        return parent::getMarque();
    }

    /**
     * {@inheritDoc}
     */
    public function setEffacer($effacer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEffacer', [$effacer]);

        return parent::setEffacer($effacer);
    }

    /**
     * {@inheritDoc}
     */
    public function getEffacer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEffacer', []);

        return parent::getEffacer();
    }

    /**
     * {@inheritDoc}
     */
    public function setCfa($cfa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCfa', [$cfa]);

        return parent::setCfa($cfa);
    }

    /**
     * {@inheritDoc}
     */
    public function getCfa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCfa', []);

        return parent::getCfa();
    }

    /**
     * {@inheritDoc}
     */
    public function setEuro($euro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEuro', [$euro]);

        return parent::setEuro($euro);
    }

    /**
     * {@inheritDoc}
     */
    public function getEuro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEuro', []);

        return parent::getEuro();
    }

    /**
     * {@inheritDoc}
     */
    public function setLivre($livre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLivre', [$livre]);

        return parent::setLivre($livre);
    }

    /**
     * {@inheritDoc}
     */
    public function getLivre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivre', []);

        return parent::getLivre();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsa($usa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsa', [$usa]);

        return parent::setUsa($usa);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsa', []);

        return parent::getUsa();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaira($naira)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaira', [$naira]);

        return parent::setNaira($naira);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaira()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaira', []);

        return parent::getNaira();
    }

    /**
     * {@inheritDoc}
     */
    public function setAll($all)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAll', [$all]);

        return parent::setAll($all);
    }

    /**
     * {@inheritDoc}
     */
    public function getAll()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAll', []);

        return parent::getAll();
    }

}
