<?php

namespace Kountac\ChatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function getMessagesByUtilisateurs($user)
    {
        $qb = $this->createQueryBuilder('m')
                ->select('m')
                ->where('m.recepteur = :user')
                ->orderBy('m.id', 'DESC')
                ->setParameter('user', $user);
        
        return $qb->getQuery()->getResult();
    }
    
}
